parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2019
  sourceType: module
  project: ./tsconfig.json

env:
  es6: true
  node: true
  mocha: true

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
  - 'prettier/@typescript-eslint'

plugins:
  - '@typescript-eslint'

rules:
  no-console: 'off'
  no-dupe-class-members: 'off'
  no-inner-declarations: 'off'
  no-redeclare: 'off'
  no-constant-condition: 'off'
  semi: 'off'

  # typescript config
  '@typescript-eslint/no-namespace': 'off'
  '@typescript-eslint/no-parameter-properties': 'off'
  '@typescript-eslint/explicit-member-accessibility': 'off'
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/no-use-before-define': 'off'

  '@typescript-eslint/indent':
    - 'warn'
    - 2
  '@typescript-eslint/member-delimiter-style':
    - 'warn'
    - multiline:
        delimiter: 'semi'
        requireLast: true
      singleline:
        delimiter: 'semi'
        requireLast: true
  '@typescript-eslint/interface-name-prefix':
    - 'warn'
    - 'never'
  '@typescript-eslint/semi':
    - 'warn'
